#!/usr/bin/env bash
# Installs a user-level `swift` wrapper so that plain `swift test --parallel` works on macOS.
#
# Why this exists:
#   SwiftPM does not add Swift Testing's framework search path, macro plugin or rpath to its
#   auto-generated test runner, and Package.swift cannot express those flags, so they have to be
#   passed on the command line. This wrapper adds them for whichever toolchain is active:
#
#   - Xcode: Testing.framework under <developer>/Platforms/MacOSX.platform/Developer/Library/
#     Frameworks; only -F and -rpath are needed (the macro plugin comes from the toolchain).
#   - Command Line Tools only: XCTest is absent entirely and Swift Testing lives under
#     /Library/Developer/CommandLineTools, so the framework path, the macro plugin path and the
#     rpath all have to be passed.
#
# Scope:
#   Writes only to $HOME/.local/bin/swift. Nothing system-wide is modified, no sudo needed.
#   Only `swift test ...` is intercepted; every other subcommand is passed through untouched.
#
# Usage:
#   Tools/install-swift-test-shim.sh
#   export PATH="$HOME/.local/bin:$PATH"   # add to ~/.zshrc to make it permanent
#   Tools/uninstall-swift-test-shim.sh     # removes it again
#
# Note: the wrapper does not change which Xcode is active. After downloading Xcode manually,
# `xcode-select -s <Xcode.app>/Contents/Developer` (needs sudo) decides what plain `swift` means.

set -euo pipefail

bin_dir="$HOME/.local/bin"
wrapper="$bin_dir/swift"
real_swift="$(command -v swift || true)"

if [ -z "$real_swift" ] || [ "$real_swift" = "$wrapper" ]; then
    real_swift="/usr/bin/swift"
fi

if [ ! -x "$real_swift" ]; then
    echo "error: no swift toolchain found at $real_swift" >&2
    exit 1
fi

mkdir -p "$bin_dir"

cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Generated by WatchBeat/Tools/install-swift-test-shim.sh
# Adds Swift Testing search paths for \`swift test\` on macOS.
real_swift="$real_swift"
command_line_tools="/Library/Developer/CommandLineTools"
clt_frameworks="\$command_line_tools/Library/Developer/Frameworks"
clt_macro_plugin="\$command_line_tools/usr/lib/swift/host/plugins/testing"

resolve_developer_dir() {
    if [ -n "\${DEVELOPER_DIR:-}" ] && [ -d "\${DEVELOPER_DIR}" ]; then
        printf '%s' "\${DEVELOPER_DIR}"; return
    fi
    local selected
    selected="\$(xcode-select -p 2>/dev/null || true)"
    if [ -n "\$selected" ] && [ "\$selected" != "\$command_line_tools" ] && [ -d "\$selected" ]; then
        printf '%s' "\$selected"; return
    fi
    local candidate
    for candidate in \\
        "/Applications/Xcode.app/Contents/Developer" \\
        "\$HOME/Downloads/Xcode.app/Contents/Developer"; do
        if [ -d "\$candidate" ]; then printf '%s' "\$candidate"; return; fi
    done
    printf ''
}

if [ "\${1:-}" != "test" ]; then
    exec "\$real_swift" "\$@"
fi

developer_dir="\$(resolve_developer_dir)"
if [ -n "\$developer_dir" ]; then
    xcode_frameworks="\$developer_dir/Platforms/MacOSX.platform/Developer/Library/Frameworks"
    if [ -d "\$xcode_frameworks/Testing.framework" ]; then
        export DEVELOPER_DIR="\$developer_dir"
        exec "\$real_swift" test "\${@:2}" \\
            -Xswiftc "-F\$xcode_frameworks" \\
            -Xlinker "-F\$xcode_frameworks" \\
            -Xlinker -rpath \\
            -Xlinker "\$xcode_frameworks"
    fi
fi

if [ -d "\$clt_frameworks/Testing.framework" ] && [ -d "\$clt_macro_plugin" ]; then
    exec "\$real_swift" test "\${@:2}" \\
        -Xswiftc "-F\$clt_frameworks" \\
        -Xswiftc -plugin-path \\
        -Xswiftc "\$clt_macro_plugin" \\
        -Xlinker "-F\$clt_frameworks" \\
        -Xlinker -rpath \\
        -Xlinker "\$clt_frameworks"
fi

exec "\$real_swift" "\$@"
EOF

chmod +x "$wrapper"

cat <<EOF
Installed: $wrapper (wraps $real_swift)

Add this to ~/.zshrc to make it permanent:
  export PATH="$HOME/.local/bin:\$PATH"

Verify:
  cd ECGCore && swift test --parallel
  cd iOS && swift test --parallel

Remove:
  Tools/uninstall-swift-test-shim.sh
EOF
